package org.campagnelab.test.editor.images.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8b180f4ab16a4c24L, 0x8f85cde0b6347aa6L, 0x677d1579f929d8b1L, "org.campagnelab.test.editor.images.structure.NodeWithIcon"))) {
        return Collections.<ConceptEditor>singletonList(new NodeWithIcon_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8b180f4ab16a4c24L, 0x8f85cde0b6347aa6L, 0x5a9b04cc5974f75cL, "org.campagnelab.test.editor.images.structure.NodeWithImage"))) {
        return Collections.<ConceptEditor>singletonList(new NodeWithImage_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
