package org.campagnelab.test.editor.images.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cells.EditorCell_Component;
import javax.swing.JComponent;
import java.awt.image.BufferedImage;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.util.MacrosFactory;
import jetbrains.mps.project.AbstractModule;
import java.io.File;
import javax.swing.JLabel;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class NodeWithImage_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_my1e4_a(editorContext, node);
  }
  private EditorCell createCollection_my1e4_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_my1e4_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_my1e4_a0(editorContext, node));
    editorCell.addEditorCell(this.createJComponent_my1e4_b0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_my1e4_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Image: ");
    editorCell.setCellId("Constant_my1e4_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createJComponent_my1e4_b0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = EditorCell_Component.createComponentCell(editorContext, node, NodeWithImage_Editor._QueryFunction_JComponent_my1e4_a1a(node, editorContext), "_my1e4_b0");
    editorCell.setCellId("JComponent_my1e4_b0");
    return editorCell;
  }
  private static JComponent _QueryFunction_JComponent_my1e4_a1a(final SNode node, final EditorContext editorContext) {
    BufferedImage image = null;
    String filename = new _FunctionTypes._return_P0_E0<String>() {
      public String invoke() {
        Language language = (Language) node.getConcept().getLanguage().getSourceModule();
        return MacrosFactory.forModule(((AbstractModule) language)).expandPath("${module}/icons/ProcessIcon-5.png");
      }
    }.invoke();
    try {
      File file = new File(filename);
      if (!(file.exists())) {
        return new JLabel("Image not available: " + filename);
      }
      image = ImageIO.read(new File(filename));
    } catch (Exception e) {
      return new JLabel("Image not available: " + filename);
    }
    ImageIcon imageIcon = new ImageIcon(image);
    JLabel jLabel = new JLabel();
    jLabel.setIcon(imageIcon);
    return jLabel;
  }
}
