package org.campagnelab.icons.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.EditorCellModel_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class EditorCell_Icon_BehaviorDescriptor extends EditorCellModel_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.icons.structure.EditorCell_Icon";
  }

}
