package org.campagnelab.editor.images;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.TemplateModuleBase;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateMappingPriorityRule;
import jetbrains.mps.generator.runtime.TemplateModel;
import jetbrains.mps.generator.runtime.TemplateUtil;
import java.util.Arrays;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.language.LanguageRuntime;

public class Generator extends TemplateModuleBase {
  public static String MODULE_REF = "b3f5c7a4-7b05-4b90-857d-985d8f2af234(org.campagnelab.editor.images#1813939192108407208)";
  private final Language sourceLanguage;
  private final Collection<TemplateMappingPriorityRule> priorities;
  private final Collection<String> referencedGenerators;
  private Collection<TemplateModel> models;

  public Generator(Language sourceLanguage) {
    this.sourceLanguage = sourceLanguage;
    priorities = TemplateUtil.asCollection(TemplateUtil.createBeforeOrTogetherRule(TemplateUtil.createRefExternal("b3f5c7a4-7b05-4b90-857d-985d8f2af234(org.campagnelab.editor.images#1813939192108407208)", TemplateUtil.createRefLocal()), TemplateUtil.createRefExternal("0647eca7-da98-422a-8a8b-6ebc0bd014ea(jetbrains.mps.lang.editor#1129914002149)", TemplateUtil.createRefLocal())));
    referencedGenerators = TemplateUtil.<String>asCollection("jetbrains.mps.lang.editor/jetbrains.mps.lang.editor#1129914002149");
  }
  @Override
  public String getAlias() {
    return "org.campagnelab.editor.images/<no name>";
  }

  @Override
  public Collection<TemplateModel> getModels() {
    if (models == null) {
      models = Arrays.asList(loadModel("org.campagnelab.editor.images.generator.template.main.TemplateModelImpl"));
    }
    return models;
  }

  @Override
  public Collection<TemplateMappingPriorityRule> getPriorities() {
    return priorities;
  }

  @Override
  public SModuleReference getReference() {
    return PersistenceFacade.getInstance().createModuleReference(MODULE_REF);
  }

  @Override
  public Collection<SLanguage> getTargetLanguages() {
    SLanguage[] rv = new SLanguage[4];
    rv[0] = MetaAdapterFactory.getLanguage(MetaIdFactory.langId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L), "jetbrains.mps.baseLanguage");
    rv[1] = MetaAdapterFactory.getLanguage(MetaIdFactory.langId(0xfd3920347849419dL, 0x907112563d152375L), "jetbrains.mps.baseLanguage.closures");
    rv[2] = MetaAdapterFactory.getLanguage(MetaIdFactory.langId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL), "jetbrains.mps.lang.editor");
    rv[3] = MetaAdapterFactory.getLanguage(MetaIdFactory.langId(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L), "jetbrains.mps.lang.smodel");
    return Arrays.asList(rv);
  }

  @Override
  public LanguageRuntime getSourceLanguage() {
    return sourceLanguage;
  }

  @Override
  public Collection<String> getReferencedModules() {
    return referencedGenerators;
  }
}
