package org.campagnelab.editor.images.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;
import jetbrains.mps.smodel.SReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import java.util.Collection;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.runtime.NodeWeaveFacility;

@Generated
public class Templatereduce__Image extends TemplateDeclarationBase {
  public Templatereduce__Image() {
  }
  public SNodeReference getTemplateNode() {
    return new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3596766244870986718");
  }
  protected SNode applyPart0(@NotNull final TemplateContext context) throws GenerationException {
    final TemplateExecutionEnvironment environment = context.getEnvironment();
    final SNode tnode1 = environment.createOutputNode(MetaAdapterFactory.getConcept(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x100d0e71cb2L, "jetbrains.mps.lang.editor.structure.CellModel_JComponent"));
    try {
      environment.nodeCopied(context, tnode1, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1879241968983622161");
      TemplateContext context1 = context.subContext();
      {
        final SNode tnode2 = environment.createOutputNode(MetaAdapterFactory.getConcept(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x111eb58c684L, "jetbrains.mps.lang.editor.structure.QueryFunction_JComponent"));
        try {
          environment.nodeCopied(context1, tnode2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1879241968983622162");
          TemplateContext context2 = context1.subContext();
          {
            final SNode tnode3 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, "jetbrains.mps.baseLanguage.structure.StatementList"));
            try {
              environment.nodeCopied(context2, tnode3, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1879241968983622163");
              TemplateContext context3 = context2.subContext();
              {
                final SNode tnode4 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
                try {
                  environment.nodeCopied(context3, tnode4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051338");
                  TemplateContext context4 = context3.subContext();
                  {
                    final SNode tnode5 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                    try {
                      environment.nodeCopied(context4, tnode5, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051337");
                      SNodeAccessUtil.setProperty(tnode5, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal"), "false");
                      SNodeAccessUtil.setProperty(tnode5, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "image");
                      TemplateContext context5 = context4.subContext();
                      {
                        final SNode tnode6 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                        try {
                          environment.nodeCopied(context5, tnode6, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051339");
                          tnode6.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode6, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:java.awt.image(JDK/)"), PersistenceFacade.getInstance().createNodeId("~BufferedImage")));
                        } finally {
                        }
                        if (tnode6 != null) {
                          tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode6);
                        }
                        // TODO validate child 
                      }
                      {
                        final SNode tnode7 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf940cd6167L, "jetbrains.mps.baseLanguage.structure.NullLiteral"));
                        try {
                          environment.nodeCopied(context5, tnode7, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051340");
                        } finally {
                        }
                        if (tnode7 != null) {
                          tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode7);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode5 != null) {
                      tnode4.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode5);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode4 != null) {
                  tnode3.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode4);
                }
                // TODO validate child 
              }
              {
                final SNode tnode8 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
                try {
                  environment.nodeCopied(context3, tnode8, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871817384");
                  TemplateContext context8 = context3.subContext();
                  {
                    final SNode tnode9 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                    try {
                      environment.nodeCopied(context8, tnode9, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871817385");
                      SNodeAccessUtil.setProperty(tnode9, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "filename");
                      TemplateContext context9 = context8.subContext();
                      {
                        final SNode tnode10 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11d47da71ecL, "jetbrains.mps.baseLanguage.structure.StringType"));
                        try {
                          environment.nodeCopied(context9, tnode10, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871839338");
                        } finally {
                        }
                        if (tnode10 != null) {
                          tnode9.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode10);
                        }
                        // TODO validate child 
                      }
                      {
                        final SNode tnode11 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                        try {
                          environment.nodeCopied(context9, tnode11, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9069541211335211125");
                          TemplateContext context11 = context9.subContext();
                          {
                            final SNode tnode12 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xfd3920347849419dL, 0x907112563d152375L, 0x1174bed3125L, "jetbrains.mps.baseLanguage.closures.structure.ClosureLiteral"));
                            try {
                              environment.nodeCopied(context11, tnode12, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9069541211335211126");
                              TemplateContext context12 = context11.subContext();
                              {
                                Collection<SNode> tlist13 = null;
                                final SNode copySrcInput13 = QueriesGenerated.sourceNodeQuery_9069541211335211129(new SourceSubstituteMacroNodeContext(context12, copySrcMacro_2l8sj1_b0a0c0c0b0c0b0e0b0c0b0d0b0c0b0c0c0c));
                                tlist13 = environment.copyNodes(TemplateUtil.singletonList(copySrcInput13), copySrcMacro_2l8sj1_b0a0c0c0b0c0b0e0b0c0b0d0b0c0b0c0c0c, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9069541211335211127", context12);
                                for (SNode child14 : TemplateUtil.asNotNull(tlist13)) {
                                  tnode12.addChild(MetaAdapterFactory.getContainmentLink(0xfd3920347849419dL, 0x907112563d152375L, 0x1174bed3125L, 0x1174bf0522fL, "body"), child14);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode12 != null) {
                              tnode11.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode12);
                            }
                            // TODO validate child 
                          }
                          {
                            final SNode tnode15 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xfd3920347849419dL, 0x907112563d152375L, 0x11d67349093L, "jetbrains.mps.baseLanguage.closures.structure.InvokeFunctionOperation"));
                            try {
                              environment.nodeCopied(context11, tnode15, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9069541211335211137");
                            } finally {
                            }
                            if (tnode15 != null) {
                              tnode11.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode15);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode11 != null) {
                          tnode9.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode11);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode9 != null) {
                      tnode8.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode9);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode8 != null) {
                  tnode3.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode8);
                }
                // TODO validate child 
              }
              {
                final SNode tnode16 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f383e6771L, "jetbrains.mps.baseLanguage.structure.TryCatchStatement"));
                try {
                  environment.nodeCopied(context3, tnode16, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051359");
                  TemplateContext context16 = context3.subContext();
                  {
                    final SNode tnode17 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f39a56e2fL, "jetbrains.mps.baseLanguage.structure.CatchClause"));
                    try {
                      environment.nodeCopied(context16, tnode17, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051360");
                      TemplateContext context17 = context16.subContext();
                      {
                        final SNode tnode18 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, "jetbrains.mps.baseLanguage.structure.StatementList"));
                        try {
                          environment.nodeCopied(context17, tnode18, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051353");
                          TemplateContext context18 = context17.subContext();
                          {
                            final SNode tnode19 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, "jetbrains.mps.baseLanguage.structure.ReturnStatement"));
                            try {
                              environment.nodeCopied(context18, tnode19, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535392844");
                              TemplateContext context19 = context18.subContext();
                              {
                                final SNode tnode20 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, "jetbrains.mps.baseLanguage.structure.GenericNewExpression"));
                                try {
                                  environment.nodeCopied(context19, tnode20, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535392845");
                                  TemplateContext context20 = context19.subContext();
                                  {
                                    final SNode tnode21 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11a59b0fbceL, "jetbrains.mps.baseLanguage.structure.ClassCreator"));
                                    try {
                                      environment.nodeCopied(context20, tnode21, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535392846");
                                      tnode21.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode21, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:javax.swing(JDK/)"), PersistenceFacade.getInstance().createNodeId("~JLabel.<init>(java.lang.String)")));
                                      TemplateContext context21 = context20.subContext();
                                      {
                                        final SNode tnode22 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7fbL, "jetbrains.mps.baseLanguage.structure.PlusExpression"));
                                        try {
                                          environment.nodeCopied(context21, tnode22, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535392847");
                                          TemplateContext context22 = context21.subContext();
                                          {
                                            final SNode tnode23 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                            try {
                                              environment.nodeCopied(context22, tnode23, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535392848");
                                              environment.resolveInTemplateLater(tnode23, "variableDeclaration", templateNode_2l8sj1_c0a1a1a2a1a3a1a2a1a2a1a2a1a2a1a2a1a4a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871817385", "filename", context22);
                                            } finally {
                                            }
                                            if (tnode23 != null) {
                                              tnode22.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11bL, "rightExpression"), tnode23);
                                            }
                                            // TODO validate child 
                                          }
                                          {
                                            final SNode tnode24 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, "jetbrains.mps.baseLanguage.structure.StringLiteral"));
                                            try {
                                              environment.nodeCopied(context22, tnode24, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535392849");
                                              SNodeAccessUtil.setProperty(tnode24, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Image not available: ");
                                            } finally {
                                            }
                                            if (tnode24 != null) {
                                              tnode22.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11cL, "leftExpression"), tnode24);
                                            }
                                            // TODO validate child 
                                          }
                                        } finally {
                                        }
                                        if (tnode22 != null) {
                                          tnode21.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode22);
                                        }
                                        // TODO validate child 
                                      }
                                    } finally {
                                    }
                                    if (tnode21 != null) {
                                      tnode20.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, 0x10ab847b486L, "creator"), tnode21);
                                    }
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                if (tnode20 != null) {
                                  tnode19.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, 0xf8cc6bf96cL, "expression"), tnode20);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode19 != null) {
                              tnode18.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode19);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode18 != null) {
                          tnode17.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f39a56e2fL, 0x10f39a6a2f2L, "catchBody"), tnode18);
                        }
                        // TODO validate child 
                      }
                      {
                        final SNode tnode25 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                        try {
                          environment.nodeCopied(context17, tnode25, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051349");
                          SNodeAccessUtil.setProperty(tnode25, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal"), "false");
                          SNodeAccessUtil.setProperty(tnode25, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "e");
                          TemplateContext context25 = context17.subContext();
                          {
                            final SNode tnode26 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                            try {
                              environment.nodeCopied(context25, tnode26, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051351");
                              tnode26.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode26, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:java.lang(JDK/)"), PersistenceFacade.getInstance().createNodeId("~Exception")));
                            } finally {
                            }
                            if (tnode26 != null) {
                              tnode25.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode26);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode25 != null) {
                          tnode17.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f39a56e2fL, 0x10f39a6a2f1L, "throwable"), tnode25);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode17 != null) {
                      tnode16.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f383e6771L, 0x10f39a8ba1fL, "catchClause"), tnode17);
                    }
                    // TODO validate child 
                  }
                  {
                    final SNode tnode27 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, "jetbrains.mps.baseLanguage.structure.StatementList"));
                    try {
                      environment.nodeCopied(context16, tnode27, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051342");
                      TemplateContext context27 = context16.subContext();
                      {
                        final SNode tnode28 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
                        try {
                          environment.nodeCopied(context27, tnode28, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535250420");
                          TemplateContext context28 = context27.subContext();
                          {
                            final SNode tnode29 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                            try {
                              environment.nodeCopied(context28, tnode29, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535250421");
                              SNodeAccessUtil.setProperty(tnode29, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "file");
                              TemplateContext context29 = context28.subContext();
                              {
                                final SNode tnode30 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                                try {
                                  environment.nodeCopied(context29, tnode30, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535250422");
                                  tnode30.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode30, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:java.io(JDK/)"), PersistenceFacade.getInstance().createNodeId("~File")));
                                } finally {
                                }
                                if (tnode30 != null) {
                                  tnode29.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode30);
                                }
                                // TODO validate child 
                              }
                              {
                                final SNode tnode31 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, "jetbrains.mps.baseLanguage.structure.GenericNewExpression"));
                                try {
                                  environment.nodeCopied(context29, tnode31, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535253189");
                                  TemplateContext context31 = context29.subContext();
                                  {
                                    final SNode tnode32 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11a59b0fbceL, "jetbrains.mps.baseLanguage.structure.ClassCreator"));
                                    try {
                                      environment.nodeCopied(context31, tnode32, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535253190");
                                      tnode32.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode32, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:java.io(JDK/)"), PersistenceFacade.getInstance().createNodeId("~File.<init>(java.lang.String)")));
                                      TemplateContext context32 = context31.subContext();
                                      {
                                        final SNode tnode33 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                        try {
                                          environment.nodeCopied(context32, tnode33, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535253191");
                                          environment.resolveInTemplateLater(tnode33, "variableDeclaration", templateNode_2l8sj1_c0a1a1a3a1a2a1a4a1a2a1a2a1a3a1a4a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871817385", "filename", context32);
                                        } finally {
                                        }
                                        if (tnode33 != null) {
                                          tnode32.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode33);
                                        }
                                        // TODO validate child 
                                      }
                                    } finally {
                                    }
                                    if (tnode32 != null) {
                                      tnode31.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, 0x10ab847b486L, "creator"), tnode32);
                                    }
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                if (tnode31 != null) {
                                  tnode29.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode31);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode29 != null) {
                              tnode28.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode29);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode28 != null) {
                          tnode27.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode28);
                        }
                        // TODO validate child 
                      }
                      {
                        final SNode tnode34 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b217L, "jetbrains.mps.baseLanguage.structure.IfStatement"));
                        try {
                          environment.nodeCopied(context27, tnode34, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535235343");
                          TemplateContext context34 = context27.subContext();
                          {
                            final SNode tnode35 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, "jetbrains.mps.baseLanguage.structure.StatementList"));
                            try {
                              environment.nodeCopied(context34, tnode35, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535235345");
                              TemplateContext context35 = context34.subContext();
                              {
                                final SNode tnode36 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, "jetbrains.mps.baseLanguage.structure.ReturnStatement"));
                                try {
                                  environment.nodeCopied(context35, tnode36, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535281379");
                                  TemplateContext context36 = context35.subContext();
                                  {
                                    final SNode tnode37 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, "jetbrains.mps.baseLanguage.structure.GenericNewExpression"));
                                    try {
                                      environment.nodeCopied(context36, tnode37, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535282480");
                                      TemplateContext context37 = context36.subContext();
                                      {
                                        final SNode tnode38 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11a59b0fbceL, "jetbrains.mps.baseLanguage.structure.ClassCreator"));
                                        try {
                                          environment.nodeCopied(context37, tnode38, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535310742");
                                          tnode38.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode38, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:javax.swing(JDK/)"), PersistenceFacade.getInstance().createNodeId("~JLabel.<init>(java.lang.String)")));
                                          TemplateContext context38 = context37.subContext();
                                          {
                                            final SNode tnode39 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7fbL, "jetbrains.mps.baseLanguage.structure.PlusExpression"));
                                            try {
                                              environment.nodeCopied(context38, tnode39, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535320283");
                                              TemplateContext context39 = context38.subContext();
                                              {
                                                final SNode tnode40 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                                try {
                                                  environment.nodeCopied(context39, tnode40, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535321428");
                                                  environment.resolveInTemplateLater(tnode40, "variableDeclaration", templateNode_2l8sj1_c0a1a1a2a1a3a1a2a1a2a1a2a1a2a1a3a1a3a1a4a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871817385", "filename", context39);
                                                } finally {
                                                }
                                                if (tnode40 != null) {
                                                  tnode39.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11bL, "rightExpression"), tnode40);
                                                }
                                                // TODO validate child 
                                              }
                                              {
                                                final SNode tnode41 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, "jetbrains.mps.baseLanguage.structure.StringLiteral"));
                                                try {
                                                  environment.nodeCopied(context39, tnode41, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535312066");
                                                  SNodeAccessUtil.setProperty(tnode41, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Image not available: ");
                                                } finally {
                                                }
                                                if (tnode41 != null) {
                                                  tnode39.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11cL, "leftExpression"), tnode41);
                                                }
                                                // TODO validate child 
                                              }
                                            } finally {
                                            }
                                            if (tnode39 != null) {
                                              tnode38.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode39);
                                            }
                                            // TODO validate child 
                                          }
                                        } finally {
                                        }
                                        if (tnode38 != null) {
                                          tnode37.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, 0x10ab847b486L, "creator"), tnode38);
                                        }
                                        // TODO validate child 
                                      }
                                    } finally {
                                    }
                                    if (tnode37 != null) {
                                      tnode36.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, 0xf8cc6bf96cL, "expression"), tnode37);
                                    }
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                if (tnode36 != null) {
                                  tnode35.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode36);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode35 != null) {
                              tnode34.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b217L, 0xf8cc56b219L, "ifTrue"), tnode35);
                            }
                            // TODO validate child 
                          }
                          {
                            final SNode tnode42 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbcf6bd10dL, "jetbrains.mps.baseLanguage.structure.NotExpression"));
                            try {
                              environment.nodeCopied(context34, tnode42, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535268342");
                              TemplateContext context42 = context34.subContext();
                              {
                                final SNode tnode43 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                                try {
                                  environment.nodeCopied(context42, tnode43, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535268344");
                                  TemplateContext context43 = context42.subContext();
                                  {
                                    final SNode tnode44 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                    try {
                                      environment.nodeCopied(context43, tnode44, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535268345");
                                      environment.resolveInTemplateLater(tnode44, "variableDeclaration", templateNode_2l8sj1_c0a1a1a2a1a2a1a3a1a3a1a3a1a4a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535250421", "file", context43);
                                    } finally {
                                    }
                                    if (tnode44 != null) {
                                      tnode43.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode44);
                                    }
                                    // TODO validate child 
                                  }
                                  {
                                    final SNode tnode45 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x118154a6332L, "jetbrains.mps.baseLanguage.structure.InstanceMethodCallOperation"));
                                    try {
                                      environment.nodeCopied(context43, tnode45, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535268346");
                                      tnode45.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode45, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:java.io(JDK/)"), PersistenceFacade.getInstance().createNodeId("~File.exists():boolean")));
                                    } finally {
                                    }
                                    if (tnode45 != null) {
                                      tnode43.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode45);
                                    }
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                if (tnode43 != null) {
                                  tnode42.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbcf6bd10dL, 0xfbcf6c30a4L, "expression"), tnode43);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode42 != null) {
                              tnode34.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b217L, 0xf8cc56b218L, "condition"), tnode42);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode34 != null) {
                          tnode27.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode34);
                        }
                        // TODO validate child 
                      }
                      {
                        final SNode tnode46 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"));
                        try {
                          environment.nodeCopied(context27, tnode46, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051343");
                          TemplateContext context46 = context27.subContext();
                          {
                            final SNode tnode47 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e96L, "jetbrains.mps.baseLanguage.structure.AssignmentExpression"));
                            try {
                              environment.nodeCopied(context46, tnode47, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051344");
                              TemplateContext context47 = context46.subContext();
                              {
                                final SNode tnode48 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                try {
                                  environment.nodeCopied(context47, tnode48, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535326679");
                                  environment.resolveInTemplateLater(tnode48, "variableDeclaration", templateNode_2l8sj1_c0a1a1a2a1a2a1a4a1a3a1a4a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051337", "image", context47);
                                } finally {
                                }
                                if (tnode48 != null) {
                                  tnode47.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e97L, "lValue"), tnode48);
                                }
                                // TODO validate child 
                              }
                              {
                                final SNode tnode49 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, "jetbrains.mps.baseLanguage.structure.StaticMethodCall"));
                                try {
                                  environment.nodeCopied(context47, tnode49, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871335560");
                                  tnode49.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), tnode49, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:javax.imageio(JDK/)"), PersistenceFacade.getInstance().createNodeId("~ImageIO")));
                                  tnode49.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode49, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:javax.imageio(JDK/)"), PersistenceFacade.getInstance().createNodeId("~ImageIO.read(java.io.File):java.awt.image.BufferedImage")));
                                  TemplateContext context49 = context47.subContext();
                                  {
                                    final SNode tnode50 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, "jetbrains.mps.baseLanguage.structure.GenericNewExpression"));
                                    try {
                                      environment.nodeCopied(context49, tnode50, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871335561");
                                      TemplateContext context50 = context49.subContext();
                                      {
                                        final SNode tnode51 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11a59b0fbceL, "jetbrains.mps.baseLanguage.structure.ClassCreator"));
                                        try {
                                          environment.nodeCopied(context50, tnode51, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871335562");
                                          tnode51.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode51, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:java.io(JDK/)"), PersistenceFacade.getInstance().createNodeId("~File.<init>(java.lang.String)")));
                                          TemplateContext context51 = context50.subContext();
                                          {
                                            final SNode tnode52 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                            try {
                                              environment.nodeCopied(context51, tnode52, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2702995834535326687");
                                              environment.resolveInTemplateLater(tnode52, "variableDeclaration", templateNode_2l8sj1_c0a1a1a3a1a2a1a4a1a3a1a2a1a4a1a3a1a4a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871817385", "filename", context51);
                                            } finally {
                                            }
                                            if (tnode52 != null) {
                                              tnode51.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode52);
                                            }
                                            // TODO validate child 
                                          }
                                        } finally {
                                        }
                                        if (tnode51 != null) {
                                          tnode50.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, 0x10ab847b486L, "creator"), tnode51);
                                        }
                                        // TODO validate child 
                                      }
                                    } finally {
                                    }
                                    if (tnode50 != null) {
                                      tnode49.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode50);
                                    }
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                if (tnode49 != null) {
                                  tnode47.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e99L, "rValue"), tnode49);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode47 != null) {
                              tnode46.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression"), tnode47);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode46 != null) {
                          tnode27.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode46);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode27 != null) {
                      tnode16.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f383e6771L, 0x10f383e83d4L, "body"), tnode27);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode16 != null) {
                  tnode3.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode16);
                }
                // TODO validate child 
              }
              {
                final SNode tnode53 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
                try {
                  environment.nodeCopied(context3, tnode53, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051362");
                  TemplateContext context53 = context3.subContext();
                  {
                    final SNode tnode54 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                    try {
                      environment.nodeCopied(context53, tnode54, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051361");
                      SNodeAccessUtil.setProperty(tnode54, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal"), "false");
                      SNodeAccessUtil.setProperty(tnode54, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "imageIcon");
                      TemplateContext context54 = context53.subContext();
                      {
                        final SNode tnode55 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                        try {
                          environment.nodeCopied(context54, tnode55, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051363");
                          tnode55.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode55, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:javax.swing(JDK/)"), PersistenceFacade.getInstance().createNodeId("~ImageIcon")));
                        } finally {
                        }
                        if (tnode55 != null) {
                          tnode54.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode55);
                        }
                        // TODO validate child 
                      }
                      {
                        final SNode tnode56 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, "jetbrains.mps.baseLanguage.structure.GenericNewExpression"));
                        try {
                          environment.nodeCopied(context54, tnode56, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871283613");
                          TemplateContext context56 = context54.subContext();
                          {
                            final SNode tnode57 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11a59b0fbceL, "jetbrains.mps.baseLanguage.structure.ClassCreator"));
                            try {
                              environment.nodeCopied(context56, tnode57, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871283711");
                              tnode57.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode57, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:javax.swing(JDK/)"), PersistenceFacade.getInstance().createNodeId("~ImageIcon.<init>(java.awt.Image)")));
                              TemplateContext context57 = context56.subContext();
                              {
                                final SNode tnode58 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                try {
                                  environment.nodeCopied(context57, tnode58, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871283712");
                                  environment.resolveInTemplateLater(tnode58, "variableDeclaration", templateNode_2l8sj1_c0a1a1a3a1a2a1a5a1a2a1a5a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051337", "image", context57);
                                } finally {
                                }
                                if (tnode58 != null) {
                                  tnode57.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode58);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode57 != null) {
                              tnode56.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, 0x10ab847b486L, "creator"), tnode57);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode56 != null) {
                          tnode54.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode56);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode54 != null) {
                      tnode53.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode54);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode53 != null) {
                  tnode3.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode53);
                }
                // TODO validate child 
              }
              {
                final SNode tnode59 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
                try {
                  environment.nodeCopied(context3, tnode59, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051367");
                  TemplateContext context59 = context3.subContext();
                  {
                    final SNode tnode60 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                    try {
                      environment.nodeCopied(context59, tnode60, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051366");
                      SNodeAccessUtil.setProperty(tnode60, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal"), "false");
                      SNodeAccessUtil.setProperty(tnode60, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "jLabel");
                      TemplateContext context60 = context59.subContext();
                      {
                        final SNode tnode61 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                        try {
                          environment.nodeCopied(context60, tnode61, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051368");
                          tnode61.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode61, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:javax.swing(JDK/)"), PersistenceFacade.getInstance().createNodeId("~JLabel")));
                        } finally {
                        }
                        if (tnode61 != null) {
                          tnode60.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode61);
                        }
                        // TODO validate child 
                      }
                      {
                        final SNode tnode62 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, "jetbrains.mps.baseLanguage.structure.GenericNewExpression"));
                        try {
                          environment.nodeCopied(context60, tnode62, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871282248");
                          TemplateContext context62 = context60.subContext();
                          {
                            final SNode tnode63 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11a59b0fbceL, "jetbrains.mps.baseLanguage.structure.ClassCreator"));
                            try {
                              environment.nodeCopied(context62, tnode63, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871282249");
                              tnode63.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode63, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:javax.swing(JDK/)"), PersistenceFacade.getInstance().createNodeId("~JLabel.<init>()")));
                            } finally {
                            }
                            if (tnode63 != null) {
                              tnode62.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, 0x10ab847b486L, "creator"), tnode63);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode62 != null) {
                          tnode60.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode62);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode60 != null) {
                      tnode59.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode60);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode59 != null) {
                  tnode3.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode59);
                }
                // TODO validate child 
              }
              {
                final SNode tnode64 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"));
                try {
                  environment.nodeCopied(context3, tnode64, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051370");
                  TemplateContext context64 = context3.subContext();
                  {
                    final SNode tnode65 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                    try {
                      environment.nodeCopied(context64, tnode65, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871054367");
                      TemplateContext context65 = context64.subContext();
                      {
                        final SNode tnode66 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                        try {
                          environment.nodeCopied(context65, tnode66, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871054366");
                          environment.resolveInTemplateLater(tnode66, "variableDeclaration", templateNode_2l8sj1_c0a1a1a2a1a2a1a7a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051366", "jLabel", context65);
                        } finally {
                        }
                        if (tnode66 != null) {
                          tnode65.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode66);
                        }
                        // TODO validate child 
                      }
                      {
                        final SNode tnode67 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x118154a6332L, "jetbrains.mps.baseLanguage.structure.InstanceMethodCallOperation"));
                        try {
                          environment.nodeCopied(context65, tnode67, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871054368");
                          tnode67.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode67, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:javax.swing(JDK/)"), PersistenceFacade.getInstance().createNodeId("~JLabel.setIcon(javax.swing.Icon):void")));
                          TemplateContext context67 = context65.subContext();
                          {
                            final SNode tnode68 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                            try {
                              environment.nodeCopied(context67, tnode68, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871054369");
                              environment.resolveInTemplateLater(tnode68, "variableDeclaration", templateNode_2l8sj1_c0a1a1a3a1a3a1a2a1a7a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051361", "imageIcon", context67);
                            } finally {
                            }
                            if (tnode68 != null) {
                              tnode67.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode68);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode67 != null) {
                          tnode65.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode67);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode65 != null) {
                      tnode64.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression"), tnode65);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode64 != null) {
                  tnode3.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode64);
                }
                // TODO validate child 
              }
              {
                final SNode tnode69 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"));
                try {
                  environment.nodeCopied(context3, tnode69, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871388329");
                  TemplateContext context69 = context3.subContext();
                  {
                    final SNode tnode70 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                    try {
                      environment.nodeCopied(context69, tnode70, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871388327");
                      environment.resolveInTemplateLater(tnode70, "variableDeclaration", templateNode_2l8sj1_c0a1a1a2a1a8a1a2a1a2a2a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3596766244871051366", "jLabel", context69);
                    } finally {
                    }
                    if (tnode70 != null) {
                      tnode69.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression"), tnode70);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode69 != null) {
                  tnode3.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode69);
                }
                // TODO validate child 
              }
            } finally {
            }
            if (tnode3 != null) {
              tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body"), tnode3);
            }
            // TODO validate child 
          }
        } finally {
        }
        if (tnode2 != null) {
          tnode1.addChild(MetaAdapterFactory.getContainmentLink(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x100d0e71cb2L, 0x111eb61aef3L, "componentProvider"), tnode2);
        }
        // TODO validate child 
      }
    } finally {
    }
    return tnode1;
  }
  @Override
  public Collection<SNode> apply(@NotNull TemplateExecutionEnvironment environment, @NotNull TemplateContext context) throws GenerationException {
    return TemplateUtil.singletonList(applyPart0(context));
  }

  @Override
  public Collection<SNode> weave(@NotNull NodeWeaveFacility.WeaveContext weaveContext, @NotNull NodeWeaveFacility weaveSupport) throws GenerationException {
    final TemplateContext templateContext = weaveSupport.getTemplateContext();
    SNode tnodepart0 = applyPart0(templateContext);
    weaveSupport.weaveNode(MetaAdapterFactory.getContainmentLink(0xb401a68083254110L, 0x8fd384331ff25befL, 0xfe43cb41d0L, 0xfe43de823bL, "contentNode"), tnodepart0);
    return TemplateUtil.singletonList(tnodepart0);
  }
  private static SNodePointer copySrcMacro_2l8sj1_b0a0c0c0b0c0b0e0b0c0b0d0b0c0b0c0c0c = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "9069541211335211128");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a2a1a3a1a2a1a2a1a2a1a2a1a2a1a4a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2702995834535392848");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a3a1a2a1a4a1a2a1a2a1a3a1a4a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2702995834535253191");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a2a1a3a1a2a1a2a1a2a1a2a1a3a1a3a1a4a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2702995834535321428");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a2a1a2a1a3a1a3a1a3a1a4a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2702995834535268345");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a2a1a2a1a4a1a3a1a4a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2702995834535326679");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a3a1a2a1a4a1a3a1a2a1a4a1a3a1a4a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2702995834535326687");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a3a1a2a1a5a1a2a1a5a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3596766244871283712");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a2a1a2a1a7a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3596766244871054366");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a3a1a3a1a2a1a7a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3596766244871054369");
  private static SNodePointer templateNode_2l8sj1_c0a1a1a2a1a8a1a2a1a2a2a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3596766244871388327");
}
