package org.campagnelab.editor.images.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.smodel.SReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import java.util.Collection;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.runtime.NodeWeaveFacility;

@Generated
public class Templatereduce__RefreshableImage extends TemplateDeclarationBase {
  public Templatereduce__RefreshableImage() {
  }
  public SNodeReference getTemplateNode() {
    return new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5058245606295170996");
  }
  protected SNode applyPart0(@NotNull final TemplateContext context) throws GenerationException {
    final TemplateExecutionEnvironment environment = context.getEnvironment();
    TemplateContext context1 = context.subContext("cellFactoryMethod");
    final SNode tnode2 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b21dL, "jetbrains.mps.baseLanguage.structure.InstanceMethodDeclaration"));
    try {
      environment.nodeCopied(context1, tnode2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090247");
      SNodeAccessUtil.setProperty(tnode2, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_1210365246785(new PropertyMacroContext(context1, "_cell_factory_method_", propertyMacro_r86c3_c0a0c0b0d0c))));
      TemplateContext context2 = context1.subContext();
      {
        final SNode tnode3 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
        try {
          environment.nodeCopied(context2, tnode3, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/6582865354027204915");
          tnode3.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode3, PersistenceFacade.getInstance().createModelReference("1ed103c3-3aa6-49b7-9c21-6765ee11f224/java:jetbrains.mps.openapi.editor.cells(MPS.Editor/)"), PersistenceFacade.getInstance().createNodeId("~EditorCell")));
        } finally {
        }
        if (tnode3 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1fdL, "returnType"), tnode3);
        }
        // TODO validate child 
      }
      {
        final SNode tnode4 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10af9586f0cL, "jetbrains.mps.baseLanguage.structure.PrivateVisibility"));
        try {
          environment.nodeCopied(context2, tnode4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1767562947359158452");
        } finally {
        }
        if (tnode4 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x112670d273fL, 0x112670d886aL, "visibility"), tnode4);
        }
        // TODO validate child 
      }
      {
        final SNode tnode5 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, "jetbrains.mps.baseLanguage.structure.StatementList"));
        try {
          environment.nodeCopied(context2, tnode5, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090248");
          TemplateContext context5 = context2.subContext();
          {
            final SNode tnode6 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
            try {
              environment.nodeCopied(context5, tnode6, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090261");
              TemplateContext context6 = context5.subContext();
              {
                final SNode tnode7 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                try {
                  environment.nodeCopied(context6, tnode7, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090262");
                  SNodeAccessUtil.setProperty(tnode7, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "editorCell");
                  TemplateContext context7 = context6.subContext();
                  {
                    final SNode tnode8 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                    try {
                      environment.nodeCopied(context7, tnode8, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5058245606295951603");
                      tnode8.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode8, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5058245606295259395")));
                    } finally {
                    }
                    if (tnode8 != null) {
                      tnode7.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode8);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode7 != null) {
                  tnode6.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode7);
                }
                // TODO validate child 
              }
            } finally {
            }
            if (tnode6 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode6);
            }
            // TODO validate child 
          }
          {
            Collection<SNode> tlist9 = null;
            if (QueriesGenerated.ifMacro_Condition_1176900701329(new IfMacroContext(context5, ifMacroRef_r86c3_b0a0b0d0b0f0d0c))) {
              final SNode tnode10 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfc092b6b77L, "jetbrains.mps.baseLanguage.structure.BlockStatement"));
              try {
                environment.nodeCopied(context5, tnode10, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139766073110");
                TemplateContext context10 = context5.subContext();
                {
                  final SNode tnode11 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, "jetbrains.mps.baseLanguage.structure.StatementList"));
                  try {
                    environment.nodeCopied(context10, tnode11, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139766073127");
                    TemplateContext context11 = context10.subContext();
                    {
                      final SNode tnode12 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
                      try {
                        environment.nodeCopied(context11, tnode12, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139768762897");
                        TemplateContext context12 = context11.subContext();
                        {
                          final SNode tnode13 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                          try {
                            environment.nodeCopied(context12, tnode13, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139768762896");
                            SNodeAccessUtil.setProperty(tnode13, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "language");
                            TemplateContext context13 = context12.subContext();
                            {
                              final SNode tnode14 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf940dabe4aL, "jetbrains.mps.baseLanguage.structure.CastExpression"));
                              try {
                                environment.nodeCopied(context13, tnode14, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2381446136244093854");
                                TemplateContext context14 = context13.subContext();
                                {
                                  final SNode tnode15 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                                  try {
                                    environment.nodeCopied(context14, tnode15, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/7446179200425304407");
                                    tnode15.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode15, PersistenceFacade.getInstance().createModelReference("6ed54515-acc8-4d1e-a16c-9fd6cfe951ea/java:jetbrains.mps.smodel(MPS.Core/)"), PersistenceFacade.getInstance().createNodeId("~Language")));
                                  } finally {
                                  }
                                  if (tnode15 != null) {
                                    tnode14.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf940dabe4aL, 0xf940dabe4bL, "type"), tnode15);
                                  }
                                  // TODO validate child 
                                }
                                {
                                  final SNode tnode16 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                                  try {
                                    environment.nodeCopied(context14, tnode16, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2381446136244093855");
                                    TemplateContext context16 = context14.subContext();
                                    {
                                      final SNode tnode17 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x118154a6332L, "jetbrains.mps.baseLanguage.structure.InstanceMethodCallOperation"));
                                      try {
                                        environment.nodeCopied(context16, tnode17, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2381446136244093856");
                                        tnode17.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode17, PersistenceFacade.getInstance().createModelReference("8865b7a8-5271-43d3-884c-6fd1d9cfdd34/java:org.jetbrains.mps.openapi.language(MPS.OpenAPI/)"), PersistenceFacade.getInstance().createNodeId("~SLanguage.getSourceModule():org.jetbrains.mps.openapi.module.SModule")));
                                      } finally {
                                      }
                                      if (tnode17 != null) {
                                        tnode16.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode17);
                                      }
                                      // TODO validate child 
                                    }
                                    {
                                      final SNode tnode18 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                                      try {
                                        environment.nodeCopied(context16, tnode18, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2381446136244093857");
                                        TemplateContext context18 = context16.subContext();
                                        {
                                          final SNode tnode19 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x118154a6332L, "jetbrains.mps.baseLanguage.structure.InstanceMethodCallOperation"));
                                          try {
                                            environment.nodeCopied(context18, tnode19, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2381446136244093858");
                                            tnode19.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode19, PersistenceFacade.getInstance().createModelReference("8865b7a8-5271-43d3-884c-6fd1d9cfdd34/java:org.jetbrains.mps.openapi.language(MPS.OpenAPI/)"), PersistenceFacade.getInstance().createNodeId("~SAbstractConcept.getLanguage():org.jetbrains.mps.openapi.language.SLanguage")));
                                          } finally {
                                          }
                                          if (tnode19 != null) {
                                            tnode18.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode19);
                                          }
                                          // TODO validate child 
                                        }
                                        {
                                          final SNode tnode20 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                                          try {
                                            environment.nodeCopied(context18, tnode20, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2381446136244093859");
                                            TemplateContext context20 = context18.subContext();
                                            {
                                              final SNode tnode21 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x118154a6332L, "jetbrains.mps.baseLanguage.structure.InstanceMethodCallOperation"));
                                              try {
                                                environment.nodeCopied(context20, tnode21, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2381446136244093860");
                                                tnode21.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode21, PersistenceFacade.getInstance().createModelReference("8865b7a8-5271-43d3-884c-6fd1d9cfdd34/java:org.jetbrains.mps.openapi.model(MPS.OpenAPI/)"), PersistenceFacade.getInstance().createNodeId("~SNode.getConcept():org.jetbrains.mps.openapi.language.SConcept")));
                                              } finally {
                                              }
                                              if (tnode21 != null) {
                                                tnode20.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode21);
                                              }
                                              // TODO validate child 
                                            }
                                            {
                                              final SNode tnode22 = environment.createOutputNode(MetaAdapterFactory.getConcept(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x10aaf6d7435L, "jetbrains.mps.lang.smodel.structure.SemanticDowncastExpression"));
                                              try {
                                                environment.nodeCopied(context20, tnode22, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2381446136244093861");
                                                TemplateContext context22 = context20.subContext();
                                                {
                                                  final SNode tnode23 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                                  try {
                                                    environment.nodeCopied(context22, tnode23, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2732009320861339052");
                                                    environment.resolveInTemplateLater(tnode23, "variableDeclaration", templateNode_r86c3_c0a1a1a2a1a3a1a3a1a3a1a3a1a3a1a2a1a2a1a2a1a1a3a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090340", "node", context22);
                                                  } finally {
                                                  }
                                                  if (tnode23 != null) {
                                                    tnode22.addChild(MetaAdapterFactory.getContainmentLink(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x10aaf6d7435L, 0x10aaf6f6e81L, "leftExpression"), tnode23);
                                                  }
                                                  // TODO validate child 
                                                }
                                              } finally {
                                              }
                                              if (tnode22 != null) {
                                                tnode20.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode22);
                                              }
                                              // TODO validate child 
                                            }
                                          } finally {
                                          }
                                          if (tnode20 != null) {
                                            tnode18.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode20);
                                          }
                                          // TODO validate child 
                                        }
                                      } finally {
                                      }
                                      if (tnode18 != null) {
                                        tnode16.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode18);
                                      }
                                      // TODO validate child 
                                    }
                                  } finally {
                                  }
                                  if (tnode16 != null) {
                                    tnode14.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf940dabe4aL, 0xf940dabe4cL, "expression"), tnode16);
                                  }
                                  // TODO validate child 
                                }
                              } finally {
                              }
                              if (tnode14 != null) {
                                tnode13.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode14);
                              }
                              // TODO validate child 
                            }
                            {
                              final SNode tnode24 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                              try {
                                environment.nodeCopied(context13, tnode24, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139768762895");
                                tnode24.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode24, PersistenceFacade.getInstance().createModelReference("6ed54515-acc8-4d1e-a16c-9fd6cfe951ea/java:jetbrains.mps.smodel(MPS.Core/)"), PersistenceFacade.getInstance().createNodeId("~Language")));
                              } finally {
                              }
                              if (tnode24 != null) {
                                tnode13.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode24);
                              }
                              // TODO validate child 
                            }
                          } finally {
                          }
                          if (tnode13 != null) {
                            tnode12.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode13);
                          }
                          // TODO validate child 
                        }
                      } finally {
                      }
                      if (tnode12 != null) {
                        tnode11.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode12);
                      }
                      // TODO validate child 
                    }
                    {
                      final SNode tnode25 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
                      try {
                        environment.nodeCopied(context11, tnode25, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139766175843");
                        TemplateContext context25 = context11.subContext();
                        {
                          final SNode tnode26 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                          try {
                            environment.nodeCopied(context25, tnode26, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139766175842");
                            SNodeAccessUtil.setProperty(tnode26, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "filename");
                            TemplateContext context26 = context25.subContext();
                            {
                              final SNode tnode27 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                              try {
                                environment.nodeCopied(context26, tnode27, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1208995316290");
                                TemplateContext context27 = context26.subContext();
                                {
                                  final SNode tnode28 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, "jetbrains.mps.baseLanguage.structure.StaticMethodCall"));
                                  try {
                                    environment.nodeCopied(context27, tnode28, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/7446179200425256004");
                                    tnode28.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode28, PersistenceFacade.getInstance().createModelReference("6ed54515-acc8-4d1e-a16c-9fd6cfe951ea/java:jetbrains.mps.util(MPS.Core/)"), PersistenceFacade.getInstance().createNodeId("~MacrosFactory.forModule(jetbrains.mps.project.AbstractModule):jetbrains.mps.util.MacroHelper")));
                                    tnode28.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), tnode28, PersistenceFacade.getInstance().createModelReference("6ed54515-acc8-4d1e-a16c-9fd6cfe951ea/java:jetbrains.mps.util(MPS.Core/)"), PersistenceFacade.getInstance().createNodeId("~MacrosFactory")));
                                    TemplateContext context28 = context27.subContext();
                                    {
                                      final SNode tnode29 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                      try {
                                        environment.nodeCopied(context28, tnode29, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/4265636116363091463");
                                        environment.resolveInTemplateLater(tnode29, "variableDeclaration", templateNode_r86c3_c0a1a1a4a1a2a1a3a1a2a1a3a1a2a1a1a3a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139768762896", "language", context28);
                                      } finally {
                                      }
                                      if (tnode29 != null) {
                                        tnode28.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode29);
                                      }
                                      // TODO validate child 
                                    }
                                  } finally {
                                  }
                                  if (tnode28 != null) {
                                    tnode27.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode28);
                                  }
                                  // TODO validate child 
                                }
                                {
                                  final SNode tnode30 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x118154a6332L, "jetbrains.mps.baseLanguage.structure.InstanceMethodCallOperation"));
                                  try {
                                    environment.nodeCopied(context27, tnode30, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1208995316291");
                                    tnode30.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode30, PersistenceFacade.getInstance().createModelReference("6ed54515-acc8-4d1e-a16c-9fd6cfe951ea/java:jetbrains.mps.util(MPS.Core/)"), PersistenceFacade.getInstance().createNodeId("~MacroHelper.expandPath(java.lang.String):java.lang.String")));
                                    TemplateContext context30 = context27.subContext();
                                    {
                                      final SNode tnode31 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, "jetbrains.mps.baseLanguage.structure.StringLiteral"));
                                      try {
                                        environment.nodeCopied(context30, tnode31, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139768629784");
                                        SNodeAccessUtil.setProperty(tnode31, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_1210377056316(new PropertyMacroContext(context30, "fileName", propertyMacro_r86c3_c0a0c0b0b0d0b0d0b0d0b0c0b0d0b0c0b0b0d0b0f0d0c))));
                                      } finally {
                                      }
                                      if (tnode31 != null) {
                                        tnode30.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode31);
                                      }
                                      // TODO validate child 
                                    }
                                  } finally {
                                  }
                                  if (tnode30 != null) {
                                    tnode27.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode30);
                                  }
                                  // TODO validate child 
                                }
                              } finally {
                              }
                              if (tnode27 != null) {
                                tnode26.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode27);
                              }
                              // TODO validate child 
                            }
                            {
                              final SNode tnode32 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11d47da71ecL, "jetbrains.mps.baseLanguage.structure.StringType"));
                              try {
                                environment.nodeCopied(context26, tnode32, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1225191498005");
                              } finally {
                              }
                              if (tnode32 != null) {
                                tnode26.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode32);
                              }
                              // TODO validate child 
                            }
                          } finally {
                          }
                          if (tnode26 != null) {
                            tnode25.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode26);
                          }
                          // TODO validate child 
                        }
                      } finally {
                      }
                      if (tnode25 != null) {
                        tnode11.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode25);
                      }
                      // TODO validate child 
                    }
                    {
                      final SNode tnode33 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"));
                      try {
                        environment.nodeCopied(context11, tnode33, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139766120172");
                        TemplateContext context33 = context11.subContext();
                        {
                          final SNode tnode34 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e96L, "jetbrains.mps.baseLanguage.structure.AssignmentExpression"));
                          try {
                            environment.nodeCopied(context33, tnode34, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139766120173");
                            TemplateContext context34 = context33.subContext();
                            {
                              final SNode tnode35 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                              try {
                                environment.nodeCopied(context34, tnode35, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/4265636116363069746");
                                environment.resolveInTemplateLater(tnode35, "variableDeclaration", templateNode_r86c3_c0a1a1a2a1a2a1a4a1a2a1a1a3a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090262", "editorCell", context34);
                              } finally {
                              }
                              if (tnode35 != null) {
                                tnode34.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e97L, "lValue"), tnode35);
                              }
                              // TODO validate child 
                            }
                            {
                              final SNode tnode36 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, "jetbrains.mps.baseLanguage.structure.StaticMethodCall"));
                              try {
                                environment.nodeCopied(context34, tnode36, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5058245606296510955");
                                tnode36.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), tnode36, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5058245606295259395")));
                                tnode36.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode36, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5058245606295263550")));
                                TemplateContext context36 = context34.subContext();
                                {
                                  final SNode tnode37 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                  try {
                                    environment.nodeCopied(context36, tnode37, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5058245606296510956");
                                    environment.resolveInTemplateLater(tnode37, "variableDeclaration", templateNode_r86c3_c0a1a1a4a1a3a1a2a1a4a1a2a1a1a3a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090338", "editorContext", context36);
                                  } finally {
                                  }
                                  if (tnode37 != null) {
                                    tnode36.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode37);
                                  }
                                  // TODO validate child 
                                }
                                {
                                  final SNode tnode38 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                  try {
                                    environment.nodeCopied(context36, tnode38, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2732009320861339351");
                                    environment.resolveInTemplateLater(tnode38, "variableDeclaration", templateNode_r86c3_c0a1a1a5a1a3a1a2a1a4a1a2a1a1a3a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090340", "node", context36);
                                  } finally {
                                  }
                                  if (tnode38 != null) {
                                    tnode36.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode38);
                                  }
                                  // TODO validate child 
                                }
                                {
                                  final SNode tnode39 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                  try {
                                    environment.nodeCopied(context36, tnode39, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5058245606296510958");
                                    environment.resolveInTemplateLater(tnode39, "variableDeclaration", templateNode_r86c3_c0a1a1a6a1a3a1a2a1a4a1a2a1a1a3a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139766175842", "filename", context36);
                                  } finally {
                                  }
                                  if (tnode39 != null) {
                                    tnode36.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode39);
                                  }
                                  // TODO validate child 
                                }
                              } finally {
                              }
                              if (tnode36 != null) {
                                tnode34.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e99L, "rValue"), tnode36);
                              }
                              // TODO validate child 
                            }
                          } finally {
                          }
                          if (tnode34 != null) {
                            tnode33.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression"), tnode34);
                          }
                          // TODO validate child 
                        }
                      } finally {
                      }
                      if (tnode33 != null) {
                        tnode11.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode33);
                      }
                      // TODO validate child 
                    }
                  } finally {
                  }
                  if (tnode11 != null) {
                    tnode10.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfc092b6b77L, 0xfc092b6b78L, "statements"), tnode11);
                  }
                  // TODO validate child 
                }
              } finally {
              }
              tlist9 = TemplateUtil.singletonList(tnode10);
            }
            for (SNode child40 : TemplateUtil.asNotNull(tlist9)) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), child40);
            }
            // TODO validate child 
          }
          {
            Collection<SNode> tlist41 = null;
            if (QueriesGenerated.ifMacro_Condition_2732009320858592076(new IfMacroContext(context5, ifMacroRef_r86c3_b0a0b0e0b0f0d0c))) {
              final SNode tnode42 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"));
              try {
                environment.nodeCopied(context5, tnode42, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2732009320858592074");
                TemplateContext context42 = context5.subContext();
                {
                  final SNode tnode43 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e96L, "jetbrains.mps.baseLanguage.structure.AssignmentExpression"));
                  try {
                    environment.nodeCopied(context42, tnode43, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2732009320858592083");
                    TemplateContext context43 = context42.subContext();
                    {
                      final SNode tnode44 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                      try {
                        environment.nodeCopied(context43, tnode44, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/2732009320858592084");
                        environment.resolveInTemplateLater(tnode44, "variableDeclaration", templateNode_r86c3_c0a1a1a2a1a2a1a1a4a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090262", "editorCell", context43);
                      } finally {
                      }
                      if (tnode44 != null) {
                        tnode43.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e97L, "lValue"), tnode44);
                      }
                      // TODO validate child 
                    }
                    {
                      final SNode tnode45 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, "jetbrains.mps.baseLanguage.structure.StaticMethodCall"));
                      try {
                        environment.nodeCopied(context43, tnode45, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/7901812471629109775");
                        tnode45.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode45, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5058245606295263573")));
                        tnode45.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), tnode45, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5058245606295259395")));
                        TemplateContext context45 = context43.subContext();
                        {
                          final SNode tnode46 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                          try {
                            environment.nodeCopied(context45, tnode46, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/7901812471629109776");
                            environment.resolveInTemplateLater(tnode46, "variableDeclaration", templateNode_r86c3_c0a1a1a4a1a3a1a2a1a1a4a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090338", "editorContext", context45);
                          } finally {
                          }
                          if (tnode46 != null) {
                            tnode45.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode46);
                          }
                          // TODO validate child 
                        }
                        {
                          final SNode tnode47 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                          try {
                            environment.nodeCopied(context45, tnode47, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/7901812471629109777");
                            environment.resolveInTemplateLater(tnode47, "variableDeclaration", templateNode_r86c3_c0a1a1a5a1a3a1a2a1a1a4a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090340", "node", context45);
                          } finally {
                          }
                          if (tnode47 != null) {
                            tnode45.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode47);
                          }
                          // TODO validate child 
                        }
                        {
                          final SNode tnode48 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                          try {
                            environment.nodeCopied(context45, tnode48, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/7901812471629109778");
                            TemplateContext context48 = context45.subContext();
                            {
                              final SNode tnode49 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xfd3920347849419dL, 0x907112563d152375L, 0x1174bed3125L, "jetbrains.mps.baseLanguage.closures.structure.ClosureLiteral"));
                              try {
                                environment.nodeCopied(context48, tnode49, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/7901812471629109779");
                                TemplateContext context49 = context48.subContext();
                                {
                                  Collection<SNode> tlist50 = null;
                                  final SNode copySrcInput50 = QueriesGenerated.sourceNodeQuery_7901812471629109782(new SourceSubstituteMacroNodeContext(context49, copySrcMacro_r86c3_b0a0c0c0b0c0b0g0b0d0b0c0b0b0e0b0f0d0c));
                                  tlist50 = environment.copyNodes(TemplateUtil.singletonList(copySrcInput50), copySrcMacro_r86c3_b0a0c0c0b0c0b0g0b0d0b0c0b0b0e0b0f0d0c, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/7901812471629109780", context49);
                                  for (SNode child51 : TemplateUtil.asNotNull(tlist50)) {
                                    tnode49.addChild(MetaAdapterFactory.getContainmentLink(0xfd3920347849419dL, 0x907112563d152375L, 0x1174bed3125L, 0x1174bf0522fL, "body"), child51);
                                  }
                                  // TODO validate child 
                                }
                              } finally {
                              }
                              if (tnode49 != null) {
                                tnode48.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode49);
                              }
                              // TODO validate child 
                            }
                            {
                              final SNode tnode52 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xfd3920347849419dL, 0x907112563d152375L, 0x11d67349093L, "jetbrains.mps.baseLanguage.closures.structure.InvokeFunctionOperation"));
                              try {
                                environment.nodeCopied(context48, tnode52, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/7901812471629109791");
                              } finally {
                              }
                              if (tnode52 != null) {
                                tnode48.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode52);
                              }
                              // TODO validate child 
                            }
                          } finally {
                          }
                          if (tnode48 != null) {
                            tnode45.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode48);
                          }
                          // TODO validate child 
                        }
                      } finally {
                      }
                      if (tnode45 != null) {
                        tnode43.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e99L, "rValue"), tnode45);
                      }
                      // TODO validate child 
                    }
                  } finally {
                  }
                  if (tnode43 != null) {
                    tnode42.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression"), tnode43);
                  }
                  // TODO validate child 
                }
              } finally {
              }
              tlist41 = TemplateUtil.singletonList(tnode42);
            }
            for (SNode child53 : TemplateUtil.asNotNull(tlist41)) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), child53);
            }
            // TODO validate child 
          }
          {
            final SNode tnode54 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b215L, "jetbrains.mps.baseLanguage.structure.Statement"));
            try {
              environment.nodeCopied(context5, tnode54, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5058245606295597760");
            } finally {
            }
            if (tnode54 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode54);
            }
            // TODO validate child 
          }
          {
            Collection<SNode> tlist55 = null;
            try {
              try {
                tlist55 = environment.applyTemplate(new SNodePointer("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)", "5170495790389304146"), new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5170495790389309596"), context5);
              } finally {
              }

            } finally {
            }
            for (SNode child56 : TemplateUtil.asNotNull(tlist55)) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), child56);
            }
            // TODO validate child 
          }
          {
            final SNode tnode57 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"));
            try {
              environment.nodeCopied(context5, tnode57, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139860898163");
              TemplateContext context57 = context5.subContext();
              {
                final SNode tnode58 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                try {
                  environment.nodeCopied(context57, tnode58, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1208995327762");
                  TemplateContext context58 = context57.subContext();
                  {
                    final SNode tnode59 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x118154a6332L, "jetbrains.mps.baseLanguage.structure.InstanceMethodCallOperation"));
                    try {
                      environment.nodeCopied(context58, tnode59, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1208995327763");
                      tnode59.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode59, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5058245606295799408")));
                      TemplateContext context59 = context58.subContext();
                      {
                        final SNode tnode60 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc59b314L, "jetbrains.mps.baseLanguage.structure.IntegerConstant"));
                        try {
                          environment.nodeCopied(context59, tnode60, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139860915942");
                          SNodeAccessUtil.setProperty(tnode60, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc59b314L, 0xf8cc59b315L, "value"), TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_1182996894663(new PropertyMacroContext(context59, "0", propertyMacro_r86c3_c0a0c0b0b0d0b0c0b0c0b0h0b0f0d0c))));
                        } finally {
                        }
                        if (tnode60 != null) {
                          tnode59.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode60);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode59 != null) {
                      tnode58.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode59);
                    }
                    // TODO validate child 
                  }
                  {
                    final SNode tnode61 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                    try {
                      environment.nodeCopied(context58, tnode61, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/4265636116363083324");
                      environment.resolveInTemplateLater(tnode61, "variableDeclaration", templateNode_r86c3_c0a1a1a3a1a2a1a7a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090262", "editorCell", context58);
                    } finally {
                    }
                    if (tnode61 != null) {
                      tnode58.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode61);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode58 != null) {
                  tnode57.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression"), tnode58);
                }
                // TODO validate child 
              }
            } finally {
            }
            if (tnode57 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode57);
            }
            // TODO validate child 
          }
          {
            final SNode tnode62 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b215L, "jetbrains.mps.baseLanguage.structure.Statement"));
            try {
              environment.nodeCopied(context5, tnode62, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5058245606295630223");
            } finally {
            }
            if (tnode62 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode62);
            }
            // TODO validate child 
          }
          {
            Collection<SNode> tlist63 = null;
            tlist63 = environment.applyTemplate(new SNodePointer("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)", "6287772348368334582"), new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "1210374656847927730"), context5);
            for (SNode child64 : TemplateUtil.asNotNull(tlist63)) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), child64);
            }
            // TODO validate child 
          }
          {
            final SNode tnode65 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, "jetbrains.mps.baseLanguage.structure.ReturnStatement"));
            try {
              environment.nodeCopied(context5, tnode65, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090335");
              TemplateContext context65 = context5.subContext();
              {
                final SNode tnode66 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                try {
                  environment.nodeCopied(context65, tnode66, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/4265636116363111253");
                  environment.resolveInTemplateLater(tnode66, "variableDeclaration", templateNode_r86c3_c0a1a1a2a1a01a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090262", "editorCell", context65);
                } finally {
                }
                if (tnode66 != null) {
                  tnode65.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, 0xf8cc6bf96cL, "expression"), tnode66);
                }
                // TODO validate child 
              }
            } finally {
            }
            if (tnode65 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode65);
            }
            // TODO validate child 
          }
        } finally {
        }
        if (tnode5 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1ffL, "body"), tnode5);
        }
        // TODO validate child 
      }
      {
        final SNode tnode67 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e94L, "jetbrains.mps.baseLanguage.structure.ParameterDeclaration"));
        try {
          environment.nodeCopied(context2, tnode67, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090338");
          SNodeAccessUtil.setProperty(tnode67, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "editorContext");
          SNodeAccessUtil.setProperty(tnode67, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal"), "true");
          TemplateContext context67 = context2.subContext();
          {
            final SNode tnode68 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
            try {
              environment.nodeCopied(context67, tnode68, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3650511996773430908");
              tnode68.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode68, PersistenceFacade.getInstance().createModelReference("1ed103c3-3aa6-49b7-9c21-6765ee11f224/java:jetbrains.mps.openapi.editor(MPS.Editor/)"), PersistenceFacade.getInstance().createNodeId("~EditorContext")));
            } finally {
            }
            if (tnode68 != null) {
              tnode67.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode68);
            }
            // TODO validate child 
          }
        } finally {
        }
        if (tnode67 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1feL, "parameter"), tnode67);
        }
        // TODO validate child 
      }
      {
        final SNode tnode69 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e94L, "jetbrains.mps.baseLanguage.structure.ParameterDeclaration"));
        try {
          environment.nodeCopied(context2, tnode69, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1139749090340");
          SNodeAccessUtil.setProperty(tnode69, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "node");
          SNodeAccessUtil.setProperty(tnode69, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal"), "true");
          TemplateContext context69 = context2.subContext();
          {
            final SNode tnode70 = environment.createOutputNode(MetaAdapterFactory.getConcept(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x108f968b3caL, "jetbrains.mps.lang.smodel.structure.SNodeType"));
            try {
              environment.nodeCopied(context69, tnode70, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/1239498049614");
            } finally {
            }
            if (tnode70 != null) {
              tnode69.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode70);
            }
            // TODO validate child 
          }
        } finally {
        }
        if (tnode69 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1feL, "parameter"), tnode69);
        }
        // TODO validate child 
      }
    } finally {
    }
    environment.registerLabel(context.getInput(), tnode2, "cellFactoryMethod");
    return tnode2;
  }
  @Override
  public Collection<SNode> apply(@NotNull TemplateExecutionEnvironment environment, @NotNull TemplateContext context) throws GenerationException {
    return TemplateUtil.singletonList(applyPart0(context));
  }

  @Override
  public Collection<SNode> weave(@NotNull NodeWeaveFacility.WeaveContext weaveContext, @NotNull NodeWeaveFacility weaveSupport) throws GenerationException {
    final TemplateContext templateContext = weaveSupport.getTemplateContext();
    SNode tnodepart0 = applyPart0(templateContext);
    weaveSupport.weaveNode(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101d9d3ca30L, 0x4a9a46de59132803L, "member"), tnodepart0);
    return TemplateUtil.singletonList(tnodepart0);
  }
  private static SNodePointer propertyMacro_r86c3_c0a0c0b0d0c = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "1139749090343");
  private static SNodePointer templateNode_r86c3_c0a1a1a2a1a3a1a3a1a3a1a3a1a3a1a2a1a2a1a2a1a1a3a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2732009320861339052");
  private static SNodePointer templateNode_r86c3_c0a1a1a4a1a2a1a3a1a2a1a3a1a2a1a1a3a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "4265636116363091463");
  private static SNodePointer propertyMacro_r86c3_c0a0c0b0b0d0b0d0b0d0b0c0b0d0b0c0b0b0d0b0f0d0c = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "1139768629785");
  private static SNodePointer templateNode_r86c3_c0a1a1a2a1a2a1a4a1a2a1a1a3a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "4265636116363069746");
  private static SNodePointer templateNode_r86c3_c0a1a1a4a1a3a1a2a1a4a1a2a1a1a3a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5058245606296510956");
  private static SNodePointer templateNode_r86c3_c0a1a1a5a1a3a1a2a1a4a1a2a1a1a3a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2732009320861339351");
  private static SNodePointer templateNode_r86c3_c0a1a1a6a1a3a1a2a1a4a1a2a1a1a3a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5058245606296510958");
  private static SNodePointer ifMacroRef_r86c3_b0a0b0d0b0f0d0c = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "1139766144948");
  private static SNodePointer templateNode_r86c3_c0a1a1a2a1a2a1a1a4a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2732009320858592084");
  private static SNodePointer templateNode_r86c3_c0a1a1a4a1a3a1a2a1a1a4a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "7901812471629109776");
  private static SNodePointer templateNode_r86c3_c0a1a1a5a1a3a1a2a1a1a4a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "7901812471629109777");
  private static SNodePointer copySrcMacro_r86c3_b0a0c0c0b0c0b0g0b0d0b0c0b0b0e0b0f0d0c = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "7901812471629109781");
  private static SNodePointer ifMacroRef_r86c3_b0a0b0e0b0f0d0c = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "2732009320858592075");
  private static SNodePointer propertyMacro_r86c3_c0a0c0b0b0d0b0c0b0c0b0h0b0f0d0c = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "1139860923194");
  private static SNodePointer templateNode_r86c3_c0a1a1a3a1a2a1a7a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "4265636116363083324");
  private static SNodePointer templateNode_r86c3_c0a1a1a2a1a01a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "4265636116363111253");
}
