package org.campagnelab.icons.swing;

/*Generated by MPS */

import javax.swing.JComponent;
import javax.swing.Icon;
import java.awt.Graphics;
import java.awt.Dimension;

public class IconAdapter extends JComponent {
  private Icon icon;

  public IconAdapter(Icon icon) {
    this.icon = icon;
  }
  @Override
  public void paintComponent(Graphics g) {
    icon.paintIcon(this, g, 0, 0);
  }
  @Override
  public Dimension getPreferredSize() {
    return new Dimension(icon.getIconWidth(), icon.getIconHeight());
  }

}
