package org.campagnelab.editor.images.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptCell_RefreshableImage = new ConceptDescriptorBuilder("org.campagnelab.editor.images.structure.Cell_RefreshableImage", MetaIdFactory.conceptId(0xa60f536b19c348f3L, 0xa6620aa30b245913L, 0x192c6815a5c992eeL)).super_("jetbrains.mps.lang.editor.structure.CellModel_Image").super_(MetaIdFactory.conceptId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x1095e12de6fL)).parents("jetbrains.mps.lang.editor.structure.CellModel_Image").parentIds(MetaIdFactory.conceptId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x1095e12de6fL)).alias("refreshable_image", "refreshable cell for an image").create();
  /*package*/ final ConceptDescriptor myConceptImage = new ConceptDescriptorBuilder("org.campagnelab.editor.images.structure.Image", MetaIdFactory.conceptId(0xa60f536b19c348f3L, 0xa6620aa30b245913L, 0x31ea47d7dda67ab7L)).super_("jetbrains.mps.lang.editor.structure.EditorCellModel").super_(MetaIdFactory.conceptId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xf9eafb9a39L)).parents("jetbrains.mps.lang.editor.structure.EditorCellModel").parentIds(MetaIdFactory.conceptId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xf9eafb9a39L)).childDescriptors(new ConceptDescriptorBuilder.Link(1176899909521L, "imagePathProvider", MetaIdFactory.conceptId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x11204aae906L), true, false, false)).children(new String[]{"imagePathProvider"}, new boolean[]{false}).alias("auto-refreshable image", "").create();
  /*package*/ final ConceptDescriptor myConceptStubCell_RefreshableImage = new ConceptDescriptorBuilder("org.campagnelab.editor.images.structure.StubCell_RefreshableImage", MetaIdFactory.conceptId(0xa60f536b19c348f3L, 0xa6620aa30b245913L, 0x39af1051e09f8817L)).super_("org.campagnelab.editor.images.structure.Cell_RefreshableImage").super_(MetaIdFactory.conceptId(0xa60f536b19c348f3L, 0xa6620aa30b245913L, 0x192c6815a5c992eeL)).parents("org.campagnelab.editor.images.structure.Cell_RefreshableImage", "jetbrains.mps.lang.core.structure.IDontSubstituteByDefault", "jetbrains.mps.lang.core.structure.IStubForAnotherConcept").parentIds(MetaIdFactory.conceptId(0xa60f536b19c348f3L, 0xa6620aa30b245913L, 0x192c6815a5c992eeL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x19796fa16a19888bL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x226fb4c3ba26d45L)).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCell_RefreshableImage, myConceptImage, myConceptStubCell_RefreshableImage);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0h, conceptFqName)) {
      case 0:
        return myConceptCell_RefreshableImage;
      case 1:
        return myConceptImage;
      case 2:
        return myConceptStubCell_RefreshableImage;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0h = new String[]{"org.campagnelab.editor.images.structure.Cell_RefreshableImage", "org.campagnelab.editor.images.structure.Image", "org.campagnelab.editor.images.structure.StubCell_RefreshableImage"};
}
