package org.campagnelab.editor.images.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.CellModel_Image_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class Cell_RefreshableImage_BehaviorDescriptor extends CellModel_Image_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.editor.images.structure.Cell_RefreshableImage";
  }

}
