package org.campagnelab.editor.images.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IStubForAnotherConcept_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class StubCell_RefreshableImage_BehaviorDescriptor extends Cell_RefreshableImage_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor, IStubForAnotherConcept_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.editor.images.structure.StubCell_RefreshableImage";
  }

}
