package org.campagnelab.workflow;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.ILanguageAspect;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import org.campagnelab.workflow.editor.EditorAspectDescriptorImpl;
import jetbrains.mps.smodel.runtime.StructureAspectDescriptor;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "c6c823fb-a9da-46e7-9850-129b0f7a7aa5(org.campagnelab.workflow)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "org.campagnelab.workflow";
  }

  @Override
  public int getVersion() {
    return 6;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("c6c823fb-a9da-46e7-9850-129b0f7a7aa5"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{"de.slisson.mps.richtext", "jetbrains.mps.baseLanguage"};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "74f88e3b-6560-4b8e-b494-6ac3e36982ec(org.campagnelab.workflow#4801669429698558903)"));
  }
  @Override
  protected <T extends ILanguageAspect> T createAspect(Class<T> aspectClass) {
    if (aspectClass == ActionAspectDescriptor.class) {
      return (T) new BaseActionAspectDescriptor();
    }
    if (aspectClass == EditorAspectDescriptor.class) {
      return (T) new EditorAspectDescriptorImpl();
    }
    if (aspectClass == StructureAspectDescriptor.class) {
      return (T) new org.campagnelab.workflow.structure.StructureAspectDescriptor();
    }
    return super.createAspect(aspectClass);
  }
}
