package org.campagnelab.workflow.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cells.EditorCell_Component;
import javax.swing.JComponent;
import javax.swing.Icon;
import jetbrains.mps.smodel.Language;
import com.bulenkov.iconloader.IconLoader;
import jetbrains.mps.util.MacrosFactory;
import jetbrains.mps.project.AbstractModule;
import java.awt.Image;
import javax.imageio.ImageIO;
import java.io.File;
import javax.swing.ImageIcon;
import org.apache.log4j.Level;
import org.campagnelab.icons.swing.IconAdapter;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class Process_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_grok3i_a(editorContext, node);
  }
  private EditorCell createCollection_grok3i_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_grok3i_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_grok3i_a0(editorContext, node));
    editorCell.addEditorCell(this.createJComponent_grok3i_b0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_grok3i_c0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_grok3i_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Process ");
    editorCell.setCellId("Constant_grok3i_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createJComponent_grok3i_b0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = EditorCell_Component.createComponentCell(editorContext, node, Process_Editor._QueryFunction_JComponent_grok3i_a1a(node, editorContext), "_grok3i_b0");
    editorCell.setCellId("JComponent_grok3i_b0");
    return editorCell;
  }
  private static JComponent _QueryFunction_JComponent_grok3i_a1a(final SNode node, final EditorContext editorContext) {
    String iconPathClean = "${module}/icons/ProcessIcon-5.png";
    Icon icon = null;
    Language language = (Language) node.getConcept().getLanguage().getSourceModule();
    try {
      if (true && language.isReadOnly()) {
        // running with language in a plugin, remove the ref to module 
        if (iconPathClean.startsWith("${module}")) {
          iconPathClean = iconPathClean.substring("${module}".length());
        }
        icon = IconLoader.getIcon(iconPathClean);
      } else {
        // running in the development environment. 
        iconPathClean = MacrosFactory.forModule(((AbstractModule) language)).expandPath(iconPathClean);
        Image image = null;
        image = ImageIO.read(new File(iconPathClean));
        icon = new ImageIcon(image);
      }

    } catch (Exception e) {
      if (LOG.isEnabledFor(Level.ERROR)) {
        LOG.error("Exception raised while trying to construct icon with path=" + iconPathClean, e);
      }
    }
    return new IconAdapter(icon);
  }
  private EditorCell createProperty_grok3i_c0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_name");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  protected static Logger LOG = LogManager.getLogger(Process_Editor.class);
}
